dist: trusty

language: generic

git:
  depth: 1

cache:
  apt: true
  timeout: 604800

env:
  matrix:
    - CABALVER=system GHCVER=system
    - CABALVER=1.16 GHCVER=7.0.1
    - CABALVER=2.24 GHCVER=8.6.3

before_install:
  - |
      # General settings
      set -e
      stty cols 120
      ulimit -c unlimited -S

      # Setting up cabal and ghc versions
      if [ "${CABALVER}${GHCVER}" != "systemsystem" ]; then
        travis_retry sudo add-apt-repository -y ppa:hvr/ghc
        travis_retry sudo apt-get update

        export CABALPKG=cabal-install-$CABALVER
        export GHCPKG=ghc-$GHCVER
        export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
      else
        export CABALPKG=cabal-install
        export GHCPKG=ghc
      fi

install:
  - travis_retry sudo apt-get install $CABALPKG $GHCPKG
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

before_script:
  - cabal configure --enable-tests --enable-benchmarks -v2
  - cabal build

script:
  - dist/build/zephir/zephir

notifications:
  email: false
